rmarkdown::render('CleanData.Rmd')
rmarkdown::render('States.Rmd')
rmarkdown::render('International.Rmd')
#rmarkdown::render('Predict.Rmd')
#system("open Predict.nb.html")
system("open CleanData.nb.html")
system("open States.nb.html")
system("open International.nb.html")
